import { Injectable } from '@nestjs/common';

import { makeExecutableSchema } from '@graphql-tools/schema';
import { GraphQLSchema } from 'graphql';
import { gql } from 'graphql-tag';

import { ScalarsExplorerService } from 'src/engine/api/graphql/services/scalars-explorer.service';
import { workspaceResolverBuilderMethodNames } from 'src/engine/api/graphql/workspace-resolver-builder/factories/factories';
import { WorkspaceResolverFactory } from 'src/engine/api/graphql/workspace-resolver-builder/workspace-resolver.factory';
import { WorkspaceGraphQLSchemaGenerator } from 'src/engine/api/graphql/workspace-schema-builder/workspace-graphql-schema.factory';
import { FeatureFlagService } from 'src/engine/core-modules/feature-flag/services/feature-flag.service';
import { FlatWorkspace } from 'src/engine/core-modules/workspace/types/flat-workspace.type';
import { DataSourceService } from 'src/engine/metadata-modules/data-source/data-source.service';

import { WorkspaceManyOrAllFlatEntityMapsCacheService } from 'src/engine/metadata-modules/flat-entity/services/workspace-many-or-all-flat-entity-maps-cache.service';
import { WorkspaceCacheStorageService } from 'src/engine/workspace-cache-storage/workspace-cache-storage.service';
import { markCompanyEditorRecords } from 'src/engine/core-modules/company-auth/company-editor-record-capabilities';

import { StockWorkspaceSchemaPartsService } from 'src/engine/api/graphql/stock-workspace-schema-parts.service';

@Injectable()
export class WorkspaceSchemaFactory {
  constructor(
    private readonly scalarsExplorerService: ScalarsExplorerService,
    private readonly workspaceGraphQLSchemaGenerator: WorkspaceGraphQLSchemaGenerator,
    private readonly workspaceResolverFactory: WorkspaceResolverFactory,
    private readonly workspaceCacheStorageService: WorkspaceCacheStorageService,
    private readonly workspaceManyOrAllFlatEntityMapsCacheService: WorkspaceManyOrAllFlatEntityMapsCacheService,
    private readonly featureFlagService: FeatureFlagService,
    private readonly dataSourceService: DataSourceService,
  ) {}

  async createGraphQLSchema(
    workspace: FlatWorkspace,
    applicationId?: string,
  ): Promise<GraphQLSchema> {
    const parts = await new StockWorkspaceSchemaPartsService(
      this.scalarsExplorerService,
      this.workspaceGraphQLSchemaGenerator,
      this.workspaceCacheStorageService,
      this.workspaceManyOrAllFlatEntityMapsCacheService,
      this.featureFlagService,
      this.dataSourceService,
    ).getSchemaParts(workspace, applicationId);
    if (!parts) return new GraphQLSchema({});
    const {
      typeDefs,
      usedScalarNames,
      flatObjectMetadataMaps,
      flatFieldMetadataMaps,
      idByNameSingular,
    } = parts;

    const autoGeneratedResolvers = await this.workspaceResolverFactory.create(
      flatObjectMetadataMaps,
      flatFieldMetadataMaps,
      idByNameSingular,
      workspaceResolverBuilderMethodNames,
    );
    const scalarsResolvers =
      this.scalarsExplorerService.getScalarResolvers(usedScalarNames);

    const executableSchema = makeExecutableSchema({
      typeDefs: gql`
        ${typeDefs}
      `,
      resolvers: {
        ...scalarsResolvers,
        ...autoGeneratedResolvers,
      },
    });

    markCompanyEditorRecords(executableSchema, flatObjectMetadataMaps);

    return executableSchema;
  }
}
