version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    exclude-paths:
      - "packages/twenty-apps/community/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    versioning-strategy: "lockfile-only"
    assignees:
      - "henrylove0"
    ignore:
      - dependency-name: "@graphql-yoga/nestjs"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@nestjs/graphql"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@ptc-org/nestjs-query-graphql"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "typeorm"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "docker"
    directory: "/packages/twenty-docker/twenty"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    assignees:
      - "henrylove0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    assignees:
      - "henrylove0"
