/*
 * Generates packages/twenty-ui/src/theme-constants/theme-{dark,light}.css from
 * the in-repo theme constants (THEME_DARK / THEME_LIGHT / themeCssVariables).
 *
 * Why: ThemeProvider reads the two CSS files at runtime. Brand tokens live in
 * TypeScript (ExeFoundryBold.ts + the ThemeDark/Light compositions), so
 * without this generator the CSS drifts and the runtime shows stale values
 * (in particular, the old Twenty blue accent instead of Exe gold).
 *
 * How: we walk `themeCssVariables` to discover the authoritative set of
 *   --t-* names, then resolve each name's value from THEME_DARK / THEME_LIGHT
 * by the same key path. Spacing is a function, so we expand it against a
 * fixed list of multipliers (identical to the one Twenty originally used).
 *
 * Values are emitted as-is — no hex→display-p3 conversion. Browsers render
 * #hex values natively; the old generator helper (git blob
 * 2d22ccfed2c0e002867c069b003796a5b32bc096) was also a pass-through.
 */

import { writeFileSync, readFileSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

import { themeCssVariables } from '../src/theme-constants/themeCssVariables';
import { THEME_DARK } from '../src/theme/constants/ThemeDark';
import { THEME_LIGHT } from '../src/theme/constants/ThemeLight';

// Avoid shadowing CJS globals — tests run under Jest+SWC which emits CJS
// and defines __dirname/__filename, while tsx runs under ESM where they
// don't exist. Use locally-scoped aliases instead.
const SCRIPT_URL = import.meta.url;
const SCRIPT_FILE = fileURLToPath(SCRIPT_URL);
const SCRIPT_DIR = dirname(SCRIPT_FILE);

const PACKAGE_ROOT = resolve(SCRIPT_DIR, '..');
const THEME_CONSTANTS_DIR = resolve(PACKAGE_ROOT, 'src/theme-constants');
const DARK_CSS = resolve(THEME_CONSTANTS_DIR, 'theme-dark.css');
const LIGHT_CSS = resolve(THEME_CONSTANTS_DIR, 'theme-light.css');

const HEADER = `/* Generated by scripts/generateThemeCss.ts — do not edit manually.
   Run \`yarn generate:theme\` to regenerate. */
`;

const NOISY_PLACEHOLDER = '__NOISY_PLACEHOLDER__';

// Matches Twenty's canonical spacing ladder: 0..32 whole numbers plus 0.5 and
// 1.5. Do not reorder — the emitted keys must match the existing theme-dark.css
// so downstream `var(--t-spacing-...)` consumers stay stable.
// eslint-disable-next-line prefer-spread
export const SPACING_VALUES: number[] = [
  ...Array.from({ length: 33 }, (_, i) => i), // 0..32
  0.5,
  1.5,
];

export const camelToKebab = (str: string): string =>
  str.replace(/([A-Z])/g, (match) => `-${match.toLowerCase()}`);

const isPlainObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const formatSpacingKey = (n: number): string => String(n).replace('.', '_');

const collectSpacingEntries = (
  name: string,
  spacingFn: (...args: number[]) => string,
): [string, string][] =>
  SPACING_VALUES.map((n) => [`--${name}-${formatSpacingKey(n)}`, spacingFn(n)]);

const collectEntriesForValue = ({
  key,
  value,
  name,
}: {
  key: string;
  value: unknown;
  name: string;
}): [string, string][] => {
  if (typeof value === 'function' && key === 'spacing') {
    return collectSpacingEntries(name, value as (...args: number[]) => string);
  }

  if (isPlainObject(value)) {
    return prepareThemeForRootCssVariableInjection({
      themeNode: value,
      prefix: name,
    });
  }

  return [[`--${name}`, String(value)]];
};

// Walks a runtime theme object and returns a flat [cssVarName, cssValue] list.
// Equivalent to Twenty's original helper — kept pass-through on purpose.
export const prepareThemeForRootCssVariableInjection = ({
  themeNode,
  prefix,
}: {
  themeNode: Record<string, unknown>;
  prefix: string;
}): [string, string][] =>
  Object.entries(themeNode).flatMap(([key, value]) => {
    const name = `${prefix}-${camelToKebab(key)}`;
    return collectEntriesForValue({ key, value, name });
  });

// Collects the *expected* variable names by walking themeCssVariables. That
// object is hand-maintained to be the canonical contract between JS code
// (consumers) and CSS (runtime). Using it as the driver means we never emit
// rogue vars and never skip ones downstream code expects.
const collectExpectedVarNames = (
  node: unknown,
  acc: Set<string> = new Set(),
): Set<string> => {
  if (typeof node === 'string') {
    const match = node.match(/var\((--[a-zA-Z0-9-]+)\)/);
    if (match !== null) acc.add(match[1]);
    return acc;
  }
  if (isPlainObject(node)) {
    for (const value of Object.values(node)) {
      collectExpectedVarNames(value, acc);
    }
  }
  return acc;
};

// Resolve a --t-foo-bar-baz variable name back to a concrete value in a
// runtime theme object. Strategy: try all key-path candidates that could
// kebab-case to the given name. We prefer the deepest match because e.g.
// `--t-background-primary` must map to `background.primary`, not a hypothetical
// root-level `backgroundPrimary`.
const resolveVarValue = (
  varName: string,
  theme: Record<string, unknown>,
  // same expansion rules used when flattening — reuse the flattener
  flat: Map<string, string>,
): string | undefined => flat.get(varName);

export const buildCssBody = (
  theme: Record<string, unknown>,
  expectedVarNames: Set<string>,
): { entries: [string, string][]; missing: string[] } => {
  const flatEntries = prepareThemeForRootCssVariableInjection({
    themeNode: theme,
    prefix: 't',
  });
  const flat = new Map(flatEntries);

  const entries: [string, string][] = [];
  const missing: string[] = [];
  for (const varName of expectedVarNames) {
    const value = resolveVarValue(varName, theme, flat);
    if (value === undefined) {
      missing.push(varName);
      continue;
    }
    entries.push([varName, value]);
  }
  return { entries, missing };
};

const formatCss = (
  selector: string,
  entries: [string, string][],
  orderedNames: string[],
): string => {
  // Preserve discovery order from themeCssVariables so diffs are readable.
  const byName = new Map(entries);
  const body = orderedNames
    .filter((n) => byName.has(n))
    .map((n) => `  ${n}: ${byName.get(n)};`)
    .join('\n');
  return `${HEADER}\n${selector} {\n${body}\n}\n`;
};

// Extract the existing --t-background-noisy data URL from a file so we can
// carry it forward when the generator itself didn't have access to the raw
// image bytes (the asset-stub loader intercepts them).
const extractExistingNoisy = (filePath: string): string | undefined => {
  if (!existsSync(filePath)) return undefined;
  const content = readFileSync(filePath, 'utf8');
  // Match end of line, not first semicolon — data: URLs contain semicolons.
  const match = content.match(/--t-background-noisy:\s*(.+?);\s*\n/);
  return match === null ? undefined : match[1].trim();
};

const replaceNoisyPlaceholder = (
  css: string,
  carriedNoisy: string | undefined,
): string => {
  if (!css.includes(NOISY_PLACEHOLDER)) return css;
  if (carriedNoisy === undefined || carriedNoisy.includes(NOISY_PLACEHOLDER)) {
    // No real value available — fall back to a plain void color so the CSS
    // stays valid. This branch only fires on a pristine tree.
    return css.replace(
      new RegExp(`url\\(${NOISY_PLACEHOLDER}\\)`, 'g'),
      '#0F0E1A',
    );
  }
  return css.replace(
    new RegExp(`url\\(${NOISY_PLACEHOLDER}\\)`, 'g'),
    carriedNoisy,
  );
};

export const orderedVarNamesFromCssVariables = (): string[] => {
  const names: string[] = [];
  const seen = new Set<string>();
  const walk = (node: unknown): void => {
    if (typeof node === 'string') {
      const match = node.match(/var\((--[a-zA-Z0-9-]+)\)/);
      if (match !== null && !seen.has(match[1])) {
        seen.add(match[1]);
        names.push(match[1]);
      }
      return;
    }
    if (isPlainObject(node)) {
      for (const value of Object.values(node)) walk(value);
    }
  };
  walk(themeCssVariables);
  // Spacing sub-keys get expanded — inject the full ladder in order.
  const spacingNames = SPACING_VALUES.map(
    (n) => `--t-spacing-${formatSpacingKey(n)}`,
  );
  // replace any individual `--t-spacing-N` / `--t-spacing-0_5` entries
  // encountered by the walk with the canonical ordered list at their
  // first-occurrence position. Match only the numeric ladder — keep
  // `--t-spacing-multiplicator` and any other non-ladder spacing vars intact.
  const isSpacingLadder = (n: string): boolean =>
    /^--t-spacing-\d+(_5)?$/.test(n);
  const firstSpacingIdx = names.findIndex(isSpacingLadder);
  const filtered = names.filter((n) => !isSpacingLadder(n));
  if (firstSpacingIdx >= 0) {
    filtered.splice(firstSpacingIdx, 0, ...spacingNames);
    return filtered;
  }
  return [...filtered, ...spacingNames];
};

export const generate = (): { dark: string; light: string } => {
  const orderedNames = orderedVarNamesFromCssVariables();
  const expectedSet = new Set(orderedNames);

  const darkCarry = extractExistingNoisy(DARK_CSS);
  const lightCarry = extractExistingNoisy(LIGHT_CSS);

  const { entries: darkEntries, missing: darkMissing } = buildCssBody(
    THEME_DARK as unknown as Record<string, unknown>,
    expectedSet,
  );
  const { entries: lightEntries, missing: lightMissing } = buildCssBody(
    THEME_LIGHT as unknown as Record<string, unknown>,
    expectedSet,
  );

  const missing = new Set([...darkMissing, ...lightMissing]);
  if (missing.size > 0) {
    // Warn but don't fail — themeCssVariables may list keys that legitimately
    // don't exist yet in both themes (e.g. parity in progress).
    // eslint-disable-next-line no-console
    console.warn(
      `[generateThemeCss] ${missing.size} expected --t-* names could not be resolved:\n  ` +
        [...missing].slice(0, 20).join('\n  ') +
        (missing.size > 20 ? `\n  ...and ${missing.size - 20} more` : ''),
    );
  }

  const dark = replaceNoisyPlaceholder(
    formatCss('.dark', darkEntries, orderedNames),
    darkCarry,
  );
  const light = replaceNoisyPlaceholder(
    formatCss('.light', lightEntries, orderedNames),
    lightCarry,
  );

  return { dark, light };
};

export const main = (): void => {
  const { dark, light } = generate();
  writeFileSync(DARK_CSS, dark, 'utf8');
  writeFileSync(LIGHT_CSS, light, 'utf8');
  // eslint-disable-next-line no-console
  console.log(
    `[generateThemeCss] wrote ${DARK_CSS.replace(PACKAGE_ROOT + '/', '')} and ${LIGHT_CSS.replace(PACKAGE_ROOT + '/', '')}`,
  );
};

// Allow `import { generate }` from tests without triggering a write. Only
// run main() when this file is executed directly via tsx/node (not when
// Jest imports it for tests).
const invokedDirectly =
  process.argv[1] !== undefined &&
  process.argv[1].endsWith(SCRIPT_FILE.split('/').pop() ?? '');

if (invokedDirectly) {
  main();
}
