// Complete shipped modules; controlled Nest/TypeORM/native/provider boundaries only.
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { readFileSync, realpathSync, mkdtempSync, writeFileSync, chmodSync, rmSync } from 'node:fs';
import { registerHooks, stripTypeScriptTypes } from 'node:module';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
const directory=new URL('../../src/engine/core-modules/company-auth/',import.meta.url);
const own=new Set(['company-browser.service.ts','company-browser.protocol.ts','company-browser.config.ts','company-auth.service.ts','company-auth.policy.ts']);
const uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const config={companyId:uuid(1),workspaceId:uuid(2),nativeSchema:'workspace_a',bindingId:uuid(3),generationId:uuid(4),audience:'crm_a',clientId:'crm_a',origin:'https://crm.a.test',brokerUrl:'http://broker:8097',authorityUrl:'http://authority:8093',clientSecret:'s'.repeat(43),bindings:new Map([[uuid(5),{subject_id:uuid(5),user_id:uuid(6),user_workspace_id:uuid(7),workspace_member_id:uuid(8)}]])};
globalThis.fixtureConfig=config;
const dependencies=`export class HttpException extends Error { constructor(message,status){super(message);this.status=status;}getStatus(){return this.status;} }
export class UnauthorizedException extends HttpException {constructor(message){super(message,401);}}export class ServiceUnavailableException extends HttpException {constructor(message){super(message,503);}}export class BadRequestException extends HttpException {constructor(message){super(message,400);}}
export const Injectable=()=>()=>{},InjectDataSource=()=>()=>{},IsNull=()=>null;
export class DataSource{};export class UserEntity{};export class UserWorkspaceEntity{};export class WorkspaceEntity{};export class RoleTargetEntity{};export class WorkspaceCacheService{};
export const fromUserEntityToFlat=x=>x,fromUserWorkspaceEntityToFlat=x=>x,fromWorkspaceEntityToFlat=x=>x,companyMemberToFlat=x=>x;
export const readCompanyAuthConfiguration=()=>globalThis.fixtureConfig;
export const COMPANY_UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;`;
registerHooks({resolve(specifier,context,next){
 if(specifier.startsWith('node:'))return next(specifier,context);
 if(specifier.startsWith('./')) {const name=specifier.slice(2)+'.ts';if(own.has(name))return{url:new URL(name,directory).href,shortCircuit:true};}
 if(specifier==='express'||specifier.startsWith('@nestjs/')||specifier==='typeorm'||specifier.startsWith('src/')||specifier==='./company-auth.config'||specifier==='./company-member-to-flat')return{url:'fixture:boundaries',shortCircuit:true};
 return next(specifier,context);
},load(url,context,next){
 if(url==='fixture:boundaries')return{format:'module',source:dependencies,shortCircuit:true};
 if(url.startsWith(directory.href)&&own.has(url.slice(directory.href.length))){let source=readFileSync(new URL(url),'utf8').replace(/^@Injectable\(\)\s*$/gm,'').replace(/@InjectDataSource\(\)\s*/g,'');return{format:'module',source:stripTypeScriptTypes(source,{mode:'transform'}),shortCircuit:true};}
 return next(url,context);
}});
const {CompanyAuthService}=await import(new URL('company-auth.service.ts',directory));
const {CompanyBrowserService,companyBrowserIngress}=await import(new URL('company-browser.service.ts',directory));
const protocol=await import(new URL('company-browser.protocol.ts',directory));
const {readCompanyBrowserConfiguration}=await import(new URL('company-browser.config.ts',directory));
const temp=realpathSync(mkdtempSync(join(tmpdir(),'owned-crm-browser-')));chmodSync(temp,0o700);const file=join(temp,'flow');writeFileSync(file,'f'.repeat(43),{mode:0o600});
process.env.CRM_COMPANY_BROWSER_ENABLED='true';process.env.CRM_COMPANY_AUTH_ORIGIN='https://auth.platform.test';process.env.CRM_COMPANY_FLOW_SECRET_FILE=file;
let trace,revoked,deleted,wrongMember,roleRevoked,providerFailure,used,providerHook;
const token='exs_'+'a'.repeat(43),code='exc_'+'b'.repeat(43),state='c'.repeat(43),verifier='d'.repeat(43);
const envelope=()=>({version:1,subject_id:uuid(5),company_id:config.companyId,product:'crm',resource_kind:'crm-workspace',native_id:config.workspaceId,binding_id:config.bindingId,generation_id:config.generationId,authz_epoch:'1',audience:config.audience,scopes:['crm:read'],current_role:'member',technical_status:'accepted',subscription_entitled:true});
let authority=envelope();
const dataSource={getRepository(entity){return{findOne:async options=>{trace.push(['native',entity.name,options]);if(entity.name==='WorkspaceEntity')return{id:config.workspaceId,activationStatus:'ACTIVE',databaseSchema:config.nativeSchema};if(entity.name==='UserEntity')return deleted?null:{id:uuid(6),isEmailVerified:true};if(entity.name==='UserWorkspaceEntity')return{id:uuid(7)};if(entity.name==='RoleTargetEntity')return roleRevoked?null:{roleId:uuid(9),role:{workspaceId:config.workspaceId}};throw Error('unknown native');}};},createQueryBuilder(){return{select(){return this},from(table){assert.equal(table,'workspace_a.workspaceMember');return this},where(sql,parameters){assert.deepEqual(parameters,{id:uuid(8),userId:uuid(6)});return this},getRawOne:async()=>wrongMember?null:{id:uuid(8)}};}};
const cache={getOrRecompute:async()=>({userWorkspaceRoleMap:{[uuid(7)]:uuid(9)}})};
const oldFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{trace.push(['provider',url,JSON.parse(options.body)]);options.signal.throwIfAborted();if(providerHook)await providerHook(options.signal);options.signal.throwIfAborted();if(providerFailure)return new Response('{}',{status:providerFailure,headers:{'content-type':'application/json'}});let value;if(url.endsWith('/token')){assert.deepEqual(JSON.parse(options.body),{grant_type:'authorization_code',code,redirect_uri:config.origin+'/company-session/callback',code_verifier:verifier,state_hash:protocol.stateHash(state)});if(used)return new Response('{}',{status:401,headers:{'content-type':'application/json'}});used=true;value={session_token:token,token_type:'Bearer',expires_in:900};}else if(url.endsWith('/introspect')){assert.deepEqual(JSON.parse(options.body),{session_token:token});if(revoked)return new Response('{}',{status:401,headers:{'content-type':'application/json'}});value=authority;}else if(url.endsWith('/revoke'))value={revoked:true};else throw Error('unexpected endpoint');return new Response(JSON.stringify(value),{status:200,headers:{'content-type':'application/json'}});};
const request=(path='/company-session/start',query='',cookies='')=>Object.assign(new EventEmitter(),{method:path.endsWith('/logout')?'POST':'GET',originalUrl:path+(query?'?'+query:''),headers:{host:'crm.a.test',...(cookies?{cookie:cookies}:{}),...(path.endsWith('/logout')?{origin:config.origin}:{})},rawHeaders:['Host','crm.a.test']});
const response=()=>Object.assign(new EventEmitter(),{headers:{},cookies:{},setHeader(k,v){this.headers[k]=v;},cookie(k,v,o){this.cookies[k]={value:v,options:o};return this;},redirect(status,location){this.statusCode=status;this.location=location;this.writableEnded=true;},status(status){this.statusCode=status;return this;},json(body){this.body=body;this.writableEnded=true;}});
let service;const reset=()=>{trace=[];revoked=deleted=wrongMember=roleRevoked=used=false;providerFailure=providerHook=undefined;authority=envelope();service=new CompanyBrowserService(new CompanyAuthService(dataSource,cache));};
const callback=()=>request('/company-session/callback','code='+code+'&state='+state,'__Host-exe_crm_flow='+protocol.sealCompanyFlow(config,service.configuration,state,verifier));
const call=async(req=request())=>{const res=response();await companyBrowserIngress(service)(req,res,()=>{throw Error('unexpected legacy dispatch');});return res;};
const denied=res=>{assert.notEqual(res.statusCode,303);assert.deepEqual(res.cookies,{});assert.equal(res.location,undefined);};
test('start has fixed registered S256 redirect and bounded secure flow without provider/native work',async()=>{reset();const res=await call();assert.equal(res.statusCode,303);const location=new URL(res.location);assert.equal(location.origin,'https://auth.platform.test');assert.equal(location.pathname,'/company-session/authorize');assert.equal(location.searchParams.get('client_id'),'crm_a');assert.equal(location.searchParams.get('code_challenge_method'),'S256');assert.match(location.searchParams.get('state'),/^[A-Za-z0-9_-]{43}$/);assert.deepEqual(trace,[]);assert.deepEqual(res.cookies.__Host_exe_crm_session,undefined);assert.equal(res.cookies['__Host-exe_crm_flow'].options.maxAge,600000);});
test('callback actual auth service queries exact operator-bound current native membership before secure publication',async()=>{reset();const res=await call(callback());assert.equal(res.statusCode,303);assert.equal(res.location,config.origin+'/company-session/status');assert.equal(res.cookies['__Host-exe_crm_session'].value,token);assert.equal(res.cookies['__Host-exe_crm_session'].options.maxAge,900000);assert.equal(res.cookies['__Host-exe_crm_session'].options.secure,true);assert.equal(res.cookies['__Host-exe_crm_session'].options.httpOnly,true);assert.equal(res.cookies['__Host-exe_crm_session'].options.sameSite,'lax');assert.equal(res.cookies['__Host-exe_crm_session'].options.path,'/');assert.equal(res.cookies['__Host-exe_crm_flow'].value,'');assert.equal(trace[1][1],config.brokerUrl+'/internal/session-broker/introspect');assert.equal(trace[2][0],'native');});
test('one-use redemption replay denied before native work',async()=>{reset();const req=callback();assert.equal((await call(req)).statusCode,303);trace=[];denied(await call(req));assert.equal(trace.length,1);});
test('forged missing or wrong-state flow denies before provider/native',async()=>{reset();for(const cookies of ['', '__Host-exe_crm_flow=bad', '__Host-exe_crm_flow='+protocol.sealCompanyFlow(config,service.configuration,'e'.repeat(43),verifier)]){const req=callback();req.headers.cookie=cookies;denied(await call(req));}assert.deepEqual(trace,[]);});
test('registration generation change invalidates the flow',async()=>{reset();const flow=protocol.sealCompanyFlow({...config,generationId:uuid(99)},service.configuration,state,verifier);const req=callback();req.headers.cookie='__Host-exe_crm_flow='+flow;denied(await call(req));assert.deepEqual(trace,[]);});
test('expired signed flow is refused',()=>{reset();const old=Date.now;try{Date.now=()=>old()-601000;const flow=protocol.sealCompanyFlow(config,service.configuration,state,verifier);Date.now=old;assert.throws(()=>protocol.openCompanyFlow(flow,state,config,service.configuration));}finally{Date.now=old;}});
test('wrong company subject binding generation scope or commercial envelope never publishes session',async()=>{for(const change of [{company_id:uuid(99)},{subject_id:uuid(99)},{generation_id:uuid(99)},{scopes:['crm:write']},{technical_status:'unverified'},{subscription_entitled:false}]){reset();authority={...envelope(),...change};denied(await call(callback()));assert.equal(trace.some(row=>row[0]==='native'),false);}});
test('native removed User exact workspaceMember or role denies after current central lookup',async()=>{for(const field of ['deleted','wrongMember','roleRevoked']){reset();if(field==='deleted')deleted=true;if(field==='wrongMember')wrongMember=true;if(field==='roleRevoked')roleRevoked=true;denied(await call(callback()));}});
test('native role revocation during provider wait observed before publication',async()=>{reset();providerHook=async()=>{roleRevoked=true;};denied(await call(callback()));});
test('current parent/session revocation denies callback and no cookies cleared',async()=>{reset();revoked=true;const res=await call(callback());assert.equal(res.statusCode,401);denied(res);});
test('provider failure preserves explicit 400 401 503 distinctions with no native access',async()=>{for(const status of [400,401,503]){reset();providerFailure=status;const res=await call(callback());assert.equal(res.statusCode,status);denied(res);assert.equal(trace.some(row=>row[0]==='native'),false);}});
test('current status accepts one own flow alongside session and rechecks native authority',async()=>{reset();const flow=protocol.sealCompanyFlow(config,service.configuration,state,verifier);const res=await call(request('/company-session/status','','__Host-exe_crm_session='+token+'; __Host-exe_crm_flow='+flow));assert.equal(res.statusCode,200);assert.deepEqual(res.cookies,{});assert.equal(trace[0][1],config.brokerUrl+'/internal/session-broker/introspect');});
test('audience-local logout checks exact Origin revokes only supplied opaque token and clears own cookies',async()=>{reset();deleted=true;const res=await call(request('/company-session/logout','','__Host-exe_crm_session='+token));assert.equal(res.statusCode,200);assert.deepEqual(res.body,{revoked:true});assert.equal(trace.length,1);assert.equal(trace[0][1],config.brokerUrl+'/internal/session-broker/revoke');assert.deepEqual(Object.keys(res.cookies).sort(),['__Host-exe_crm_flow','__Host-exe_crm_session']);});
test('foreign host Origin legacy bearer/native cookies selectors and duplicate headers denied before work',async()=>{reset();const cases=[req=>req.headers.host='crm.b.test',req=>req.headers.origin='https://foreign.test',req=>{req.headers.authorization='Bearer eyJlegacy';req.rawHeaders.push('Authorization','Bearer eyJlegacy');},req=>req.headers.cookie='sid=native',req=>req.originalUrl+='?workspace_id='+uuid(99),req=>req.rawHeaders.push('host','crm.a.test'),req=>{req.headers['x-user']='native';req.rawHeaders.push('X-User','native');}];for(const change of cases){const req=request();change(req);denied(await call(req));}assert.deepEqual(trace,[]);});
test('only top-level start/callback permits cross-host navigation not fetch or business status',async()=>{reset();const req=request();req.headers['sec-fetch-site']='cross-site';req.headers['sec-fetch-mode']='navigate';req.headers['sec-fetch-dest']='document';assert.equal((await call(req)).statusCode,303);req.headers['sec-fetch-mode']='cors';denied(await call(req));const status=request('/company-session/status','','__Host-exe_crm_session='+token);status.headers['sec-fetch-site']='cross-site';denied(await call(status));});
test('callback redirect target accepts authenticated document navigation with whole-chain same-site or cross-site metadata',async()=>{for(const site of ['same-site','cross-site']){reset();const callbackResponse=await call(callback());assert.equal(callbackResponse.statusCode,303);const req=request(new URL(callbackResponse.location).pathname,'','__Host-exe_crm_session='+callbackResponse.cookies['__Host-exe_crm_session'].value);req.headers['sec-fetch-site']=site;req.headers['sec-fetch-mode']='navigate';req.headers['sec-fetch-dest']='document';trace=[];const result=await call(req);assert.equal(result.statusCode,200);assert.deepEqual(result.body,{enabled:true,authenticated:true});assert.equal(trace[0][1],config.brokerUrl+'/internal/session-broker/introspect');assert.ok(trace.some(row=>row[0]==='native'));revoked=true;denied(await call(req));revoked=false;roleRevoked=true;denied(await call(req));}});
test('status redirect exception refuses fetch iframe missing session flow-only foreign Origin and logout',async()=>{for(const site of ['same-site','cross-site']){reset();const valid=()=>{const req=request('/company-session/status','','__Host-exe_crm_session='+token);req.headers['sec-fetch-site']=site;req.headers['sec-fetch-mode']='navigate';req.headers['sec-fetch-dest']='document';return req;};for(const change of [req=>req.headers['sec-fetch-mode']='cors',req=>req.headers['sec-fetch-dest']='iframe',req=>delete req.headers['sec-fetch-mode'],req=>delete req.headers['sec-fetch-dest'],req=>delete req.headers.cookie,req=>req.headers.cookie='__Host-exe_crm_flow='+protocol.sealCompanyFlow(config,service.configuration,state,verifier),req=>req.headers.origin='https://foreign.test']){const req=valid();change(req);denied(await call(req));}const logout=request('/company-session/logout','','__Host-exe_crm_session='+token);logout.headers['sec-fetch-site']=site;logout.headers['sec-fetch-mode']='navigate';logout.headers['sec-fetch-dest']='document';denied(await call(logout));const business=valid();business.originalUrl='/rest/people?depth=0&limit=2';assert.equal(service.accepts(business),false);assert.throws(()=>protocol.browserRequest(business,config));assert.deepEqual(trace,[]);}});
test('response parser rejects duplicate escaped nested malformed and nonUTF8 provider shapes',()=>{for(const raw of ['{"revoked":true,"revoked":false}','{"\\u0072evoked":true}','{"revoked":{}}','\ufeff{"revoked":true}',Buffer.from([0xff])])assert.throws(()=>protocol.parseBrowserProvider(Buffer.from(raw)));assert.deepEqual(protocol.parseBrowserProvider(Buffer.from('{"revoked":true}')),{revoked:true});});
test('aborted request during actual provider wait produces no positive result or native query',async()=>{reset();const req=callback();providerHook=async signal=>{req.emit('aborted');signal.throwIfAborted();};denied(await call(req));assert.equal(trace.some(row=>row[0]==='native'),false);});
test('late native acknowledged return suppresses cookies/positive serialization',async()=>{reset();const original=Date.now;try{let now=original();Date.now=()=>now;cache.getOrRecompute=async()=>{now+=10000;return{userWorkspaceRoleMap:{[uuid(7)]:uuid(9)}}};denied(await call(callback()));}finally{Date.now=original;cache.getOrRecompute=async()=>({userWorkspaceRoleMap:{[uuid(7)]:uuid(9)}});}});
test('fixed default-off partial secret permissions and unsafe origins refuse browser startup',()=>{const save={...process.env};try{delete process.env.CRM_COMPANY_AUTH_ORIGIN;delete process.env.CRM_COMPANY_FLOW_SECRET_FILE;delete process.env.CRM_COMPANY_BROWSER_ENABLED;assert.equal(readCompanyBrowserConfiguration(config),null);process.env.CRM_COMPANY_BROWSER_ENABLED='true';assert.throws(()=>readCompanyBrowserConfiguration(config));process.env.CRM_COMPANY_AUTH_ORIGIN='https://auth.platform.test';process.env.CRM_COMPANY_FLOW_SECRET_FILE=file;chmodSync(file,0o644);assert.throws(()=>readCompanyBrowserConfiguration(config));chmodSync(file,0o600);for(const value of ['https://auth.platform.test/path','http://auth.platform.test','https://erp.a.test']){process.env.CRM_COMPANY_AUTH_ORIGIN=value;assert.throws(()=>readCompanyBrowserConfiguration(config));}}finally{for(const name of Object.keys(process.env))if(!(name in save))delete process.env[name];Object.assign(process.env,save);}});
test('finite shared-company rate budget denies without new provider/native work',async()=>{reset();for(let i=0;i<120;i++)assert.equal((await call()).statusCode,303);const res=await call();assert.equal(res.statusCode,429);denied(res);assert.deepEqual(trace,[]);});
test('browser ingress preserves default-off and unrelated legacy dispatch',async()=>{reset();let passed=0;await companyBrowserIngress(service)(request('/rest/people','depth=0&limit=2'),response(),()=>passed++);assert.equal(passed,1);const original=service.configuration;service.configuration=null;await companyBrowserIngress(service)(request(),response(),()=>passed++);assert.equal(passed,2);service.configuration=original;});
test.after(()=>{globalThis.fetch=oldFetch;rmSync(temp,{recursive:true});});
