// Generated by exe-db/scripts/company-contract.mjs; edit the central source.
// Policy digest (SHA-256): 790e6bc8d9b78c31d33fa4fce3b57717c952d225b078eef442726daf6c9ec85c
// Canonical company access policy. Apps receive an opaque session and this
// envelope; GoTrue signing keys and parent tokens stay at the identity boundary.
export const COMPANY_ACCESS_VERSION = 1 as const;
export const COMPANY_PRODUCTS = ['crm', 'erp', 'wiki'] as const;
export const COMPANY_ACCESS_FIELDS = [
  'version',
  'subject_id',
  'company_id',
  'product',
  'resource_kind',
  'binding_id',
  'native_id',
  'generation_id',
  'authz_epoch',
  'audience',
  'scopes',
  'current_role',
  'technical_status',
  'subscription_entitled',
] as const;
export const COMPANY_UUID =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
export type CompanyProduct = (typeof COMPANY_PRODUCTS)[number];
export type CompanyAccess = {
  version: 1;
  subject_id: string;
  company_id: string;
  product: CompanyProduct;
  resource_kind: 'crm-workspace' | 'erp-site' | 'wiki-instance';
  binding_id: string;
  native_id: string;
  generation_id: string;
  authz_epoch: string;
  audience: string;
  scopes: readonly string[];
  current_role: 'owner' | 'member';
  technical_status: 'accepted';
  subscription_entitled: true;
};
export type CompanyBinding = Pick<
  CompanyAccess,
  | 'company_id'
  | 'product'
  | 'binding_id'
  | 'native_id'
  | 'generation_id'
  | 'audience'
>;
const kinds = {
  crm: 'crm-workspace',
  erp: 'erp-site',
  wiki: 'wiki-instance',
} as const;
function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}
function uuid(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    COMPANY_UUID.test(value) &&
    value !== '00000000-0000-0000-0000-000000000000'
  );
}
function hasControlCharacters(value: string): boolean {
  for (let index = 0; index < value.length; index++) {
    const code = value.charCodeAt(index);
    if (code <= 31 || code === 127) return true;
  }
  return false;
}
function nativeId(product: CompanyProduct, value: unknown): boolean {
  if (typeof value !== 'string') return false;
  if (product === 'crm') return uuid(value);
  if (product === 'wiki') return /^[a-z0-9][a-z0-9_-]{0,79}$/.test(value);
  return (
    value.length <= 252 &&
    value.startsWith('erp.') &&
    /^[a-z]{2,63}$/.test(value.split('.').slice(-1)[0]) &&
    value.slice(4).split('.').length > 1 &&
    value
      .slice(4)
      .split('.')
      .every((label) => /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label))
  );
}
export function companyAccess(
  value: unknown,
  binding?: CompanyBinding,
): CompanyAccess | null {
  if (
    !record(value) ||
    Object.keys(value).length !== COMPANY_ACCESS_FIELDS.length ||
    COMPANY_ACCESS_FIELDS.some(
      (field) => !Object.prototype.hasOwnProperty.call(value, field),
    )
  )
    return null;
  const copy: Record<string, unknown> = {};
  for (const field of COMPANY_ACCESS_FIELDS) copy[field] = value[field];
  if (
    copy.version !== COMPANY_ACCESS_VERSION ||
    ![
      copy.subject_id,
      copy.company_id,
      copy.binding_id,
      copy.generation_id,
    ].every(uuid) ||
    !COMPANY_PRODUCTS.includes(copy.product as CompanyProduct)
  )
    return null;
  const product = copy.product as CompanyProduct;
  if (
    copy.resource_kind !== kinds[product] ||
    !nativeId(product, copy.native_id) ||
    typeof copy.authz_epoch !== 'string' ||
    !/^[1-9][0-9]{0,18}$/.test(copy.authz_epoch) ||
    typeof copy.audience !== 'string' ||
    !/^[a-z][a-z0-9_-]{2,63}$/.test(copy.audience) ||
    (copy.current_role !== 'owner' && copy.current_role !== 'member') ||
    copy.technical_status !== 'accepted' ||
    copy.subscription_entitled !== true ||
    !Array.isArray(copy.scopes) ||
    copy.scopes.length !== 1 ||
    copy.scopes[0] !== product + ':read'
  )
    return null;
  if (
    binding &&
    (
      [
        'company_id',
        'product',
        'binding_id',
        'native_id',
        'generation_id',
        'audience',
      ] as const
    ).some((field) => copy[field] !== binding[field])
  )
    return null;
  return { ...(copy as unknown as CompanyAccess), scopes: [product + ':read'] };
}

export type GoTrueIdentity = {
  subject_id: string;
  email: string;
  email_confirmed: true;
  parent_session_id: string;
  parent_exp: number;
};
export type GoTrueResult =
  | { status: 200; identity: GoTrueIdentity }
  | { status: 401 | 403 };
// Call only after the exact bearer has passed a live GoTrue /user request.
// Decoding claims alone is never proof of identity or current session validity.
export function goTrueIdentity(
  user: unknown,
  claims: unknown,
  now = Date.now(),
  audience = 'authenticated',
): GoTrueResult {
  if (
    !record(user) ||
    !record(claims) ||
    !Number.isFinite(now) ||
    typeof audience !== 'string' ||
    !/^[A-Za-z0-9._~=+/:-]+$/.test(audience) ||
    !uuid(user.id) ||
    user.id === '00000000-0000-0000-0000-000000000000' ||
    typeof user.email !== 'string' ||
    user.email.trim().length < 3 ||
    user.email.length > 320 ||
    hasControlCharacters(user.email) ||
    user.role !== 'authenticated' ||
    user.aud !== audience ||
    user.is_anonymous !== false ||
    user.deleted_at ||
    user.is_active === false ||
    user.disabled === true ||
    (user.banned_until !== undefined &&
      user.banned_until !== null &&
      user.banned_until !== '' &&
      (typeof user.banned_until !== 'string' ||
        !Number.isFinite(Date.parse(user.banned_until)) ||
        Date.parse(user.banned_until) > now)) ||
    claims.sub !== user.id ||
    claims.role !== 'authenticated' ||
    claims.aud !== audience ||
    !uuid(claims.session_id) ||
    claims.session_id === '00000000-0000-0000-0000-000000000000' ||
    typeof claims.exp !== 'number' ||
    !Number.isSafeInteger(claims.exp) ||
    claims.exp <= now / 1000
  )
    return { status: 401 };
  if (
    typeof user.email_confirmed_at !== 'string' ||
    !Number.isFinite(Date.parse(user.email_confirmed_at)) ||
    Date.parse(user.email_confirmed_at) > now
  )
    return { status: 403 };
  return {
    status: 200,
    identity: {
      subject_id: user.id,
      email: user.email.trim().toLowerCase(),
      email_confirmed: true,
      parent_session_id: claims.session_id,
      parent_exp: claims.exp,
    },
  };
}

export type CompanySetup = {
  version: 1;
  company_id: string;
  state: 'pending' | 'ready' | 'failed';
  phase: 'queued' | 'provisioning' | 'verification' | 'ready' | 'attention';
};
// This describes environment setup only. It does not grant app access.
export function companySetup(
  value: unknown,
  company: string,
): CompanySetup | null {
  if (
    !record(value) ||
    Object.keys(value).sort().join(',') !== 'company_id,phase,state,version' ||
    value.version !== 1 ||
    value.company_id !== company ||
    !uuid(company) ||
    typeof value.phase !== 'string'
  )
    return null;
  const valid =
    (value.state === 'pending' &&
      ['queued', 'provisioning', 'verification'].includes(value.phase)) ||
    (value.state === 'ready' && value.phase === 'ready') ||
    (value.state === 'failed' && value.phase === 'attention');
  return valid
    ? ({
        version: 1,
        company_id: company,
        state: value.state,
        phase: value.phase,
      } as CompanySetup)
    : null;
}
